"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Button(object):
    __slots__ = ["pressed"]

    def __init__(self):
        self.pressed = False

    def encode(self):
        buf = BytesIO()
        buf.write(Button._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.pressed))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Button._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Button._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Button()
        self.pressed = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if Button in parents: return 0
        tmphash = (0x43543a64543d162c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Button._packed_fingerprint is None:
            Button._packed_fingerprint = struct.pack(">Q", Button._get_hash_recursive([]))
        return Button._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

